### PR TITLE
Depend on newer versions of net-scp

### PR DESCRIPTION
**Pull request by johanneskastl**
- depend on bundler 2.0.x
- depend on net-scp 2.0.x

### CODE REVIEW

**Comment by dcermak** [comment]
Any update on this?

**Comment by johanneskastl** [comment]
Seems like at least the bundler dependency was updated in the meantime:
https://github.com/invernizzi/vagrant-scp/commit/dbefe6bcdd082a3d8547260f3126ecb457006ece

**Comment by dcermak** [comment]
@johanneskastl I believe this PR is not needed anymore, as vagrant-scp now no longer uses `~>` but simply requires a lower bound on the version number.

**Comment by johanneskastl** [comment]
> @johanneskastl I believe this PR is not needed anymore, as vagrant-scp now no longer uses `~>` but simply requires a lower bound on the version number.

You are right!

**Pull request closed without merging**
